'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("KCSubCTCV3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property GreenRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("GreenRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property KCSubCTC() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("KCSubCTC", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftDownGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftDownGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftDownLocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftDownLocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftDownOccupied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftDownOccupied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftDownUnlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftDownUnlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftUpGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftUpGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftUpLocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftUpLocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftUpOccupied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftUpOccupied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockLeftUpUnlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockLeftUpUnlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightDownGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightDownGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightDownLocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightDownLocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightDownOccupied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightDownOccupied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightDownUnlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightDownUnlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightUpGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightUpGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightUpLocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightUpLocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightUpOccupied() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightUpOccupied", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LockRightUpUnlocked() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LockRightUpUnlocked", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RedRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RedRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficClearedEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficClearedEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficClearedEastEnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficClearedEastEnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficClearedWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficClearedWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficClearedWestEnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficClearedWestEnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficNoneEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficNoneEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficNoneWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficNoneWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficOccupiedEast() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficOccupiedEast", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficOccupiedEastEnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficOccupiedEastEnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficOccupiedWest() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficOccupiedWest", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TrafficOccupiedWestEnd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TrafficOccupiedWestEnd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownNormalGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownNormalGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownNormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownNormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownReverseGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownReverseGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftDownReverseRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftDownReverseRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpNormalGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpNormalGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpNormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpNormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpReverseGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpReverseGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutLeftUpReverseRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutLeftUpReverseRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownNormalGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownNormalGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownNormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownNormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownReverseGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownReverseGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightDownReverseRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightDownReverseRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpBlank() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpBlank", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpNormalGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpNormalGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpNormalRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpNormalRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpReverse() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpReverse", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpReverseGreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpReverseGreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TurnoutRightUpReverseRed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TurnoutRightUpReverseRed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhiteLeft() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteLeft", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhiteRight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteRight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
